# Generated by Django 5.0.6 on 2024-08-05 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackinghistory',
            old_name='CurrentBalance',
            new_name='current_balance',
        ),
    ]
