# Generated by Django 5.0.6 on 2024-08-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_requestlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlogs',
            name='request_path',
            field=models.CharField(default=1234, max_length=100),
            preserve_default=False,
        ),
    ]
